name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Lint_and_Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          cd starter/backend
          pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Install flake8
        run: |
          cd starter/backend
          pip install flake8

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test

      - name: Run linting
        run: |
          cd starter/backend
          pipenv run lint

