name: Backend Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools and dependencies
        run: |
          python -m pip install --upgrade pip
          cd starter/backend
          pip install pipenv
          pipenv install
          pip install flake8

      - name: Run linting
        run: |
          cd starter/backend
          pipenv run lint

  Test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tools and dependencies
        run: |
          python -m pip install --upgrade pip
          cd starter/backend
          pip install pipenv
          pipenv install
          pip install flake8
      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build image and run
        run: |
          cd starter/backend
          docker build -t mp-backend:latest .
          docker run -p 5000:5000 --name mp-backend -d mp-backend
          curl http://localhost:5000/movies